### ISSUE TITLE
feature request: email template optimized for outlook

### ISSUE THREAD

**Issue by iainmwallace** [rich-iannone/blastula#145]
Hi,

Would it be possible to create an e-mail template that is optimized for Microsoft Outlook? The default e-mail template has a very narrow width which isn't optimal for my corporate environment where everyone is using the same e-mail client, Microsoft Outlook.

Thanks

Iain

**Comment by andrie** [comment]
related to #144

**Comment by rich-iannone** [comment]
Hi @iainmwallace a question: would this entirely be for sending emails through Connect? If so, it would focus the amount of work that's required

I believe the message part is around 600px (which probably appears even smaller in Outlook due to default zoom levels); would you be able to share a screenshot of what you're seeing? That would show us just how much we'd need to increase the width.

**Comment by iainmwallace** [comment]
Hi @rich-iannone,

Yeah, this is entirely for sending e-mails through Connect

Attached is a screenshot of the e-mail in full screen mode
<img width="1679" alt="Screen Shot 2020-03-20 at 10 17 51 AM" src="https://user-images.githubusercontent.com/12777558/77172376-3d0a2300-6a94-11ea-8f36-9e274f63aa11.png">

Hope that helps, but please let me know if there is anything else I can do 

Thanks,

Iain

**Comment by MadhulikaTanuboddi** [comment]
Related to https://github.com/rich-iannone/blastula/pull/160

**Comment by rich-iannone** [comment]
Fixed in #178

**Comment by rich-iannone** [comment]
@iainmwallace @andrie Just wanted to let you both know that this fix (wider emails as the new default) is now available in the newly released **blastula** package in CRAN (0.3.2). Thanks for submitting the issue @iainmwallace and for your patience during the process of fixing.
