### ISSUE TITLE
Memory error for long list with for loop

### ISSUE THREAD

**Issue by riskcede** [rich-iannone/blastula#147]
Firstly, thanks for the package, its by far my favourite to use for sending emails.

Im getting an error when I use a for loop to send out a lot of emails. 

Error in curl::curl_fetch_memory(url, handle = h) : MAIL failed: 421

I get it after about 80 emails sent out successfully.

Im not sure if it can be related to gmail? Im using gmail.

If i rerun the script for the remaining emails it sends out the rest, so it might be an R memory issue?

Below is an example, i stripped out most of the code, but even this loop still produces the same error. Hope you can reproduce it without my email details...

library(blastula)
library(tidyverse)

for(i in 1:100){

  e_eamil <- 'my email address'
  
  email <- compose_email(body = 'hi', footer = 'bi')
  
  email %>%
    smtp_send(
      from = "our gmail address",
      to = e_eamil,
      subject = "Blastula test",
      credentials = creds_file('gmail_creds')
    )
}

Regards
Jan

**Comment by rich-iannone** [comment]
This looks to be an error sent by the SMTP server:

```
SMTP Error 421
421 Server busy, try again later. The SMTP error 421 is normally used for temporary problems on the mail server or a problem with the recipients email account. Some mail providers might also return 421 after you reached a limit (restriction) on your mail account (see SMTP Error 451 below).
```

I think it's Gmail because it's not set up for bulk emailing. There are some options though. Getting access to an SMTP server with looser restrictions will help. You might also consider sending emails in batches to recipients in the BCC field.

For my part, I'll do some research on how to make this easier through blastula.

**Comment by kristymazoo** [comment]
I was also running into this issue using outlook, only it stopped at 5 emails instead of 80. is that something that's unique to the email server?

**Comment by kristymazoo** [comment]
a colleague of mind was able to find a workaround where adding a sleep component resolves the cap of emails through a loop (by allowing some delay). 

for the above example, something like this: 

for(i in 1:100){

e_eamil <- 'my email address'

email <- compose_email(body = 'hi', footer = 'bi')

email %>%
smtp_send(
from = "our gmail address",
to = e_eamil,
subject = "Blastula test",
credentials = creds_file('gmail_creds')
)

`add a necessary delay so they dont' block you`

**Sys.sleep(5)**

}

**Comment by rich-iannone** [comment]
This is a good idea because most email services have a policy of stopping suspected spam (and quickly sending lotsa emails looks pretty spammy). I had a lot of luck in the recent past with the smtp2go service, which is more forgiving with bulk emailing. Even the free tier is really good. I used the following credentials setup:

```
creds(
  user = "username",
  host = "mail.smtp2go.com",
  port = 465,
  use_ssl = TRUE
)
```

I'd still recommend a small sleep between iterations/sends but I've had a lot more consistency with this service than Gmail and Outlook.
