### ISSUE TITLE
Bare Line Feed Characters Error

### ISSUE THREAD

**Issue by DataHippo93** [rich-iannone/blastula#16]
When I send an email from Blastula using my SMTP server any emails sent to gmail return as undeliverable. Any ideas how to remove the Break line feeds which are causing this error?

**Comment by edelosre** [comment]
I had the same error and I was able to send a html file to gmail using mailsend (which blastula sends parameters to). The encoding parameter in mailsend needs to be set as 

enc-type "base64" 
instead of
enc-type "us-ascii"

It looks like setting the parameter _attach_encodings_ in the _send_email_out_ function (from blastula) to

attach_encodings = "base64" 

Should be able to change this, however, it seems to currently not do anything and needs to be fixed(?).

**Comment by rich-iannone** [comment]
I know that this issue was quite a while back and you may have moved on, however, could you try out the new `smtp_send()` function? Installation instructions for the `mailsend-go` dependency are in this vignette: https://rich-iannone.github.io/blastula/articles/sending_using_smtp.html.

Going to close this issue.
