### ISSUE TITLE
Suppressing CSS in e-mails sent via Outlook365

### ISSUE THREAD

**Issue by coatless** [rich-iannone/blastula#161]
E-mails being sent via outlook365 are showing CSS regardless of whether `md()` is being used on development version: 

<img width="943" alt="Screen Shot 2020-03-23 at 4 05 48 PM" src="https://user-images.githubusercontent.com/833642/77363161-342d8180-6d20-11ea-8a35-53791e17363d.png">

```r
utils::packageVersion("blastula")
# [1] '0.3.1.9000'
```

**Comment by rich-iannone** [comment]
This is similar to #162 . Could you update to the latest version of `master` with `devtools::install_github("rich-iannone/blastula")`. Use the code in the related issue to ensure that the SHA matches with the latest. 

The reason I ask for this is because #153 addressed this but is perhaps not a complete fix.

**Comment by coatless** [comment]
@rich-iannone upgraded to master and the problem seems to be resolved:

<img width="1057" alt="Screen Shot 2020-03-25 at 1 51 30 PM" src="https://user-images.githubusercontent.com/833642/77574318-d2942100-6e9f-11ea-97ef-33cf7d257f4a.png">

**Comment by rich-iannone** [comment]
Thank you very much for getting back to me with the update!

**Comment by coatless** [comment]
@rich-iannone thanks for the rockin' package that didn't require me to use `rJava` :)
